# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-12-03 20:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20211203_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 20, 57, 11, 285505, tzinfo=utc)),
        ),
    ]
