# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-12-07 12:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20211207_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 12, 47, 1, 567798, tzinfo=utc)),
        ),
    ]
