# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-02-17 07:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20220217_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 7, 41, 58, 243965, tzinfo=utc)),
        ),
    ]
